output "cluster_id"               { value = aws_eks_cluster.this.id }
output "cluster_arn"              { value = aws_eks_cluster.this.arn }
output "cluster_endpoint"         { value = aws_eks_cluster.this.endpoint }
output "cluster_version"          { value = aws_eks_cluster.this.version }
output "cluster_oidc_issuer_url"  { value = aws_eks_cluster.this.identity[0].oidc[0].issuer }
output "cluster_security_group_id"{ value = aws_eks_cluster.this.vpc_config[0].cluster_security_group_id }
output "node_group_system"        { value = aws_eks_node_group.system.id }
output "node_group_application"   { value = aws_eks_node_group.application.id }
output "oidc_provider_arn"        { value = aws_iam_openid_connect_provider.eks.arn }
